import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const expoArabic = localFont({
  src: [
    {
      path: "./fonts/ExpoArabic/ArbFONTS-ExpoArabic-Book.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ExpoArabic/alfont_com_AlFont_com_ExpoArabic-SemiBold.ttf",
      weight: "700",
      style: "normal",
    },
    // Add other font weights/styles as needed
    {
      path: "./fonts/ExpoArabic/alfont_com_AlFont_com_ExpoArabic-Bold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-expo-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Intimate Relationship",
  description: "Generated by MTN Dev Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className={expoArabic.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
